spring.application.name=medical-system
#Production Server
server.port=18000
#Stage Server
#server.port=8095
server.address=0.0.0.0
#server.servlet.contextPath=/medicaldisbursement
server.servlet.contextPath=/api

#eureka.client.service-url.defaultzone=http://localhost:8761/eureka/


#UAT Db Configuration
spring.datasource.url=jdbc:postgresql://10.96.38.32:5432/medical_dispensary?currentSchema=medical
spring.datasource.username=ntr_med_disp
spring.datasource.password=ntr_med_disp__@2024
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Sit db
#spring.datasource.url=jdbc:postgresql://172.16.32.168:5432/medical_dispensary?currentSchema=medical
#spring.datasource.username=ntr_med_disp
#spring.datasource.password=ntr_med_disp__@2024
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Staging db
#spring.datasource.url=jdbc:postgresql://10.252.112.188:5432/medical_dispensary?currentSchema=medical
#spring.datasource.username=ntr_med_disp
#spring.datasource.password=234$gfdhX2
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect




#JPA
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl




#KEY
secret.key=f0e2b7a3c8d5e1b4a7c0e2d5a8b1e3d9f4a7c0e2d5a8b1e3d9f4a7c0e2d5a8b1e3d9f4a7c0e2d5a8b1e3d9f4a7c0e2d5a8b1e3d9f4a7c0e2d5a8b1e3d9f4a7c0e2d5a8b1e3d9f4a7c0e2d5a8b1e3d9f4a7c0e2d5a8b1e3d9f4a7c0e2d5a8b1e3d9f4

#File Upload
#local
#file.path=\\hrmsPayrollDocs\\
#file.temp.path=\\hrmsPayrollTemp\\
#file.slash= \\
#file.lastIndexslash =\\

# uat server file path
file.path= //home//kpmguser//projects//medicineDisbursement//
file.temp.path= //home//kpmguser//medicineDisbursement//
file.slash= //
file.lastIndexslash =/

#sit file path
#file.path= //home//kpmg//jarwar//medicineDisbursement//
#file.temp.path= //home//kpmg//medicineDisbursement//
#file.slash= //
#file.lastIndexslash =/

#staging file path
#file.path= //home//apmsidc//docs//medicineDisbursement//
#file.temp.path= //home//apmsidc//medicineDisbursement//
#file.slash= //
#file.lastIndexslash =/


## eureka connection
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false

server.servlet.session.cookie.path=/
server.servlet.session.cookie.http-only=true
#server.servlet.session.cookie.secure=false

# Compression
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain
server.compression.min-response-size=1024
server.compression.excluded-user-agents=MSIE 6.0,httpClient4